### ISSUE TITLE
Porting to 0.4.1 Questions

### ISSUE THREAD

**Issue by NightOwl888** [synhershko/Spatial4n#9]
For the Lucene.Net project, I am porting Spatial4n to 0.4.1 of Spatial4j. But I have some questions about the project structure.

First of all, why are there 2 libraries, Spatial4n.Core and Spatial4n.Core.NTS? They contain nearly all the same types except for the Nts related stuff, but without any docs it is difficult to work out why this division was made. If there is a valid need to make them separate, is there some compelling reason why conditional compilation symbols were not used instead of 2 separate projects?

Secondly, 0.4.1 contains [some calls](https://github.com/locationtech/spatial4j/blob/spatial4j-0.4.1/src/main/java/com/spatial4j/core/io/WktShapeParser.java#L392) to the `Character.isJavaIdentifierPart()` method. After some research, it seems that the [closest match for this method is `SyntaxFacts.IsIdentifierPartCharacter()`](http://stackoverflow.com/a/34268364/181087), which is part of Roslyn. The gotcha is that Roslyn requires .NET 4.5 and I noticed that you were setup before to target 3.5 and 4.0. I could create a more hackish solution so these legacy frameworks are supported, but it seems like it might be a lost cause at this point (3.5 is still supported, but other than that Microsoft officially doesn't support anything less than 4.5.2). Which frameworks do we need to support here other than 4.5.1 for Lucene.Net?

**Comment by synhershko** [comment]
We shipped LuceneNet spatial in two flavors, one full with NTS support (that adds a lot of functionality), and one without (with perhaps weaker / stripped functionality). I don't remember if it was the same with Java or not. I think it was because NTS was a heavy dependency. Let's survey the current state of the Spatial sub-project to see if that is still necessary.

Watch out of strong naming the dependencies have. Spatial4n can remain strong named (although I prefer it didn't), but LuceneNet will probably not get strong named.

I'm ok with requiring .NET 4.5+ to use the Spatial subproject. I am not sure I want to add a dependency o Roslyn. This is in the Java WKT reader - why does the WKT reader need to know about syntax? Also, note the 2 methods are NOT interchangable, one is expecting Java syntax the other C# syntax.

**Comment by NightOwl888** [comment]
> I'm ok with requiring .NET 4.5+ to use the Spatial subproject. I am not sure I want to add a dependency o Roslyn. This is in the Java WKT reader - why does the WKT reader need to know about syntax? Also, note the 2 methods are NOT interchangable, one is expecting Java syntax the other C# syntax.

Actually, I couldn't work out how to get the Roslyn dependency that was required to do that. The [JavaDoc is clear](http://docs.oracle.com/javase/7/docs/api/java/lang/Character.html#isJavaIdentifierPart(char)) on what the requirements are, so I was able to put together a solution that works exactly like it does in Java, which as you mentioned is probably a closer match anyway.

And yes, it is as clear as mud why Spatial requires this :).

**Comment by synhershko** [comment]
> And yes, it is as clear as mud why Spatial requires this :).

Let's just drop it then - and not support the edge case of WKT with Java syntax.
